blank_issues_enabled: false
contact_links:
  - name: Report a security issue
    url: https://bugs.php.net/report.php?bug_type=Security
    about: Please report security issues in this private bug tracker.
