name: Remove needs feedback label

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Remove needs feedback label
        uses: octokit/request-action@v2.x
        continue-on-error: true
        with:
          route: DELETE /repos/:repository/issues/:issue/labels/:label
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          label: "Status: Needs Feedback"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
